name: Build and Deploy Payload CMS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build Payload CMS
        run: pnpm build
        env:
            PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
            MONGODB_URI: ${{ secrets.MONGODB_URI }}
            NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}

      - name: Check MongoDB URI scheme
        run: echo "${MONGODB_URI:0:12}"
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}


      - name: Upload Files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: ".next,package.json,public,payload.config.ts,dist,node_modules"
          target: "~/payload-app"
